---
facebook:
  appId: 205992766192598
  appSecret: 5fac7e9d41a9bfbbfc3b7e3d2a869dce

---
spring:
  profiles: cloud
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri}

