server:
  port: 8888


logging:
  level:
    com.netflix.discovery: 'OFF'
    

spring:
  platform:
    config:
      server:
        uri: https://github.com/joshlong/spring-doge-microservice-configuration

